package com.ev.user_service.enums;

import lombok.Getter;

@Getter
public enum PermissionName {
    // Vehicle permissions
    VIEW_VEHICLES("VIEW_VEHICLES"),
    COMPARE_VEHICLES("COMPARE_VEHICLES"),
    MANAGE_VEHICLES("MANAGE_VEHICLES"),
    MANAGE_PRICING("MANAGE_PRICING"),

    // Sales permissions
    CREATE_QUOTATION("CREATE_QUOTATION"),
    CREATE_ORDER("CREATE_ORDER"),
    CREATE_CONTRACT("CREATE_CONTRACT"),
    APPROVE_ORDERS("APPROVE_ORDERS"),
    VIEW_ALL_DEALER_ORDERS("VIEW_ALL_DEALER_ORDERS"),

    // Customer permissions (for dealers managing customers)
    MANAGE_OWN_CUSTOMERS("MANAGE_OWN_CUSTOMERS"),
    CREATE_APPOINTMENT("CREATE_APPOINTMENT"),
    CREATE_FEEDBACK("CREATE_FEEDBACK"),
    VIEW_ALL_DEALER_CUSTOMERS("VIEW_ALL_DEALER_CUSTOMERS"),

    // B2C Customer permissions (for end customers)
    VIEW_OWN_PROFILE("VIEW_OWN_PROFILE"),
    UPDATE_OWN_PROFILE("UPDATE_OWN_PROFILE"),
    VIEW_OWN_ORDERS("VIEW_OWN_ORDERS"),
    CREATE_OWN_ORDER("CREATE_OWN_ORDER"),
    CANCEL_OWN_ORDER("CANCEL_OWN_ORDER"),
    VIEW_OWN_PAYMENTS("VIEW_OWN_PAYMENTS"),
    MAKE_PAYMENT("MAKE_PAYMENT"),
    REQUEST_TEST_DRIVE("REQUEST_TEST_DRIVE"),
    VIEW_PROMOTIONS("VIEW_PROMOTIONS"),

    // Inventory permissions
    VIEW_DEALER_INVENTORY("VIEW_DEALER_INVENTORY"),
    REQUEST_STOCK("REQUEST_STOCK"),
    VIEW_CENTRAL_INVENTORY("VIEW_CENTRAL_INVENTORY"),
    ALLOCATE_VEHICLES("ALLOCATE_VEHICLES"),

    // Payment permissions
    PROCESS_PAYMENT("PROCESS_PAYMENT"),

    // Report permissions
    VIEW_DEALER_REPORTS("VIEW_DEALER_REPORTS"),
    VIEW_SYSTEM_REPORTS("VIEW_SYSTEM_REPORTS"),
    VIEW_AI_REPORTS("VIEW_AI_REPORTS"),

    // Management permissions
    MANAGE_DEALER_STAFF("MANAGE_DEALER_STAFF"),
    MANAGE_DEALERS("MANAGE_DEALERS"),
    MANAGE_USERS("MANAGE_USERS"),
    MANAGE_PROMOTIONS("MANAGE_PROMOTIONS"),

    // System permissions
    FULL_SYSTEM_ACCESS("FULL_SYSTEM_ACCESS"),
    SYSTEM_CONFIG("SYSTEM_CONFIG");

    private final String name;

    PermissionName(String name) {
        this.name = name;
    }
}