-- Insert sample charging stations data for Vietnam
-- These are example locations - adjust coordinates and details as needed

INSERT INTO charging_stations (
    station_name, address, city, province, 
    latitude, longitude, 
    total_chargers, available_chargers, 
    charger_types, max_power_kw, 
    pricing_info, status, operating_hours, 
    phone_number, description, amenities, is_public,
    created_at, updated_at
) VALUES 
(
    'Trạm sạc VinFast Times City',
    '458 Minh Khai, Hai Bà Trưng, Hà Nội',
    'Hà Nội',
    'Hà Nội',
    20.9983, 105.8644,
    8, 6,
    'CCS, Type 2',
    150,
    'Miễn phí cho khách hàng VinFast trong 3 năm đầu',
    'ACTIVE',
    '24/7',
    '1900 23 23 89',
    'Trạm sạc nhanh tại trung tâm thương mại Times City',
    'WiFi, Nhà hàng, Khu vui chơi trẻ em',
    TRUE,
    NOW(), NOW()
),
(
    'Trạm sạc VinFast Royal City',
    '72A Nguyễn Trãi, Thanh Xuân, Hà Nội',
    'Hà Nội',
    'Hà Nội',
    20.9980, 105.8095,
    6, 5,
    'CCS, Type 2, CHAdeMO',
    150,
    'Miễn phí cho khách hàng VinFast trong 3 năm đầu',
    'ACTIVE',
    '24/7',
    '1900 23 23 89',
    'Trạm sạc tại Royal City Vincom Mega Mall',
    'WiFi, Nhà hàng, Siêu thị, Cinema',
    TRUE,
    NOW(), NOW()
),
(
    'Trạm sạc VinFast Landmark 81',
    'Vinhomes Central Park, 720A Điện Biên Phủ, Bình Thạnh, TP.HCM',
    'Hồ Chí Minh',
    'Hồ Chí Minh',
    10.7943, 106.7212,
    10, 8,
    'CCS, Type 2',
    180,
    'Miễn phí cho khách hàng VinFast trong 3 năm đầu',
    'ACTIVE',
    '24/7',
    '1900 23 23 89',
    'Trạm sạc siêu nhanh tại Landmark 81',
    'WiFi, Nhà hàng cao cấp, Shopping mall, Spa',
    TRUE,
    NOW(), NOW()
),
(
    'Trạm sạc VinFast Vivo City',
    '1058 Nguyễn Văn Linh, Quận 7, TP.HCM',
    'Hồ Chí Minh',
    'Hồ Chí Minh',
    10.7335, 106.7025,
    8, 7,
    'CCS, Type 2, CHAdeMO',
    150,
    'Miễn phí cho khách hàng VinFast trong 3 năm đầu',
    'ACTIVE',
    '06:00-23:00',
    '1900 23 23 89',
    'Trạm sạc tại SC Vivo City',
    'WiFi, Nhà hàng, Siêu thị, Rạp chiếu phim',
    TRUE,
    NOW(), NOW()
),
(
    'Trạm sạc VinFast Đà Nẵng',
    'Vincom Plaza Đà Nẵng, 910A Ngô Quyền, Sơn Trà, Đà Nẵng',
    'Đà Nẵng',
    'Đà Nẵng',
    16.0634, 108.2253,
    6, 4,
    'CCS, Type 2',
    150,
    'Miễn phí cho khách hàng VinFast trong 3 năm đầu',
    'ACTIVE',
    '24/7',
    '1900 23 23 89',
    'Trạm sạc tại Vincom Đà Nẵng',
    'WiFi, Nhà hàng, Siêu thị',
    TRUE,
    NOW(), NOW()
),
(
    'Trạm sạc VinFast Hải Phòng',
    'Vincom Plaza Hải Phòng, 106 Trần Phú, Ngô Quyền, Hải Phòng',
    'Hải Phòng',
    'Hải Phòng',
    20.8566, 106.6886,
    6, 6,
    'CCS, Type 2',
    150,
    'Miễn phí cho khách hàng VinFast trong 3 năm đầu',
    'ACTIVE',
    '08:00-22:00',
    '1900 23 23 89',
    'Trạm sạc tại Vincom Plaza Hải Phòng',
    'WiFi, Nhà hàng, Siêu thị, Rạp chiếu phim',
    TRUE,
    NOW(), NOW()
),
(
    'Trạm sạc VinFast Cần Thơ',
    'Vincom Plaza Xuân Khánh, 209 Đường 30/4, Xuân Khánh, Ninh Kiều, Cần Thơ',
    'Cần Thơ',
    'Cần Thơ',
    10.0452, 105.7469,
    4, 3,
    'CCS, Type 2',
    150,
    'Miễn phí cho khách hàng VinFast trong 3 năm đầu',
    'ACTIVE',
    '08:00-22:00',
    '1900 23 23 89',
    'Trạm sạc tại Vincom Cần Thơ',
    'WiFi, Nhà hàng, Siêu thị',
    TRUE,
    NOW(), NOW()
),
(
    'Trạm sạc VinFast Nha Trang',
    'Vincom Plaza Nha Trang, 190 Hoàng Hoa Thám, Lộc Thọ, Nha Trang',
    'Nha Trang',
    'Khánh Hòa',
    12.2451, 109.1943,
    6, 5,
    'CCS, Type 2',
    150,
    'Miễn phí cho khách hàng VinFast trong 3 năm đầu',
    'ACTIVE',
    '08:00-22:00',
    '1900 23 23 89',
    'Trạm sạc tại Vincom Plaza Nha Trang',
    'WiFi, Nhà hàng, Siêu thị',
    TRUE,
    NOW(), NOW()
),
(
    'Trạm sạc EVN Hà Nội',
    '18 Trần Nguyên Hãn, Hoàn Kiếm, Hà Nội',
    'Hà Nội',
    'Hà Nội',
    21.0245, 105.8412,
    4, 3,
    'Type 2, CHAdeMO',
    50,
    '5,000 VNĐ/kWh',
    'ACTIVE',
    '06:00-22:00',
    '19001006',
    'Trạm sạc công cộng của EVN',
    'WiFi',
    TRUE,
    NOW(), NOW()
),
(
    'Trạm sạc Green SM Mega Hà Nội',
    'Big C Thăng Long, 222 Trần Duy Hưng, Cầu Giấy, Hà Nội',
    'Hà Nội',
    'Hà Nội',
    21.0086, 105.7978,
    4, 4,
    'CCS, Type 2',
    100,
    '4,500 VNĐ/kWh',
    'ACTIVE',
    '07:00-23:00',
    '0987654321',
    'Trạm sạc tại Big C Thăng Long',
    'WiFi, Siêu thị, Nhà hàng',
    TRUE,
    NOW(), NOW()
);
